# Generated by Django 5.1.2 on 2025-01-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
